### PR TITLE
Disable meridiem select

### LINKED ISSUE #19: Meridiem Selector & clock button appear editable when read-only="true"
When the meridiem selector is available but the directive is marked as `read-only`, the user can still click on the meridiem selector, but not make any choices. It would look better if this was not clickable at all - `md-select` has a `disabled` option to disable this.

Additionally, when the directive is in `read-only`, the clock icon has `cursor: pointer`, even though it's not editable. This should probably be set to `cursor: default` to stay consistent with `md-datepicker`.

Codepen of the issues: 

https://codepen.io/cbacon91/pen/wqBrgY

### PR DESCRIPTION
**Pull request by JaspervdK**
fixes: https://github.com/classlinkinc/angular-material-time-picker/issues/19

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
Hi @Andreasbaaserud will there be a new version published to npm soon?

**Comment by Andreasbaaserud** [comment]
Hi @AdriVanHoudt yes I will publish one soon. I was hoping to have time to publish this fix with a few more fixes.

Do you need this before the weekend?

**Comment by AdriVanHoudt** [comment]
Not super important, if you release soon then that would be greatly appreciated 🎉

**Comment by Andreasbaaserud** [comment]
Did you see I released v1.0.8 on NPM?

**Comment by AdriVanHoudt** [comment]
Jup, awesome thanks!

**Pull request merged**
